### ISSUE TITLE
can not run iOS Simulator - Invalid Data: Please select a module

### ISSUE THREAD

**Issue by sdyura** [multi-os-engine-community/moe-ide-integration#3]
I am new to multi-os-engine and have been trying to run the example app
i downloaded AS and am following the guide on: https://doc.multi-os-engine.org/multi-os-engine/3_getting_started/2_moe_samples/MOE_samples.html

it says:
1) "Edit Configurations..."
2) "Add new configuration"
3) "Multi-OS Engine iOS Application"

and it shows that the module should say "iOS" but instead it is empty for me and i am unable to select anything

<img width="1440" alt="Screenshot 2021-06-08 at 12 10 04" src="https://user-images.githubusercontent.com/56878790/121175104-9786cf00-c852-11eb-8a63-d0155a218602.png">

**Comment by Noisyfox** [comment]
Have you tried https://discuss.multi-os-engine.org/t/android-studio-4-2/2892/5?u=noisyfox

**Comment by sdyura** [comment]
hi, i have tried that now, but it still does not work, same problem, the modules list is empty
i have managed to get around this for now by using a old version of Android Studio (3.2.1)
but for anyone new to MOE this will be a big problem

**Comment by Noisyfox** [comment]
![image](https://user-images.githubusercontent.com/1537155/121545273-b8ffda80-ca4d-11eb-816f-50f800e4cea0.png)
Could you double check if this task list is not empty?

**Comment by sdyura** [comment]
after a few restarts and gradle syncs it IS now showing the drop-down!
it now shows 2 modules in the list ["projectName", "projectName:ios"]
